Add csv headers.
Biomapas/B.LambdaLayerCommon pull request #14
Opened 2020-12-17 14:18 UTC by ignaloidas

2020-12-17 14:37 UTC, robertasstankevicius commented
Update HISTORY.md

2020-12-17 14:40 UTC, ignaloidas commented
> Update HISTORY.md

Done

2020-12-17 14:47 UTC, robertasstankevicius approved these changes

2020-12-18 08:47 UTC, laimonassutkus requested changes

2020-12-18 08:47 UTC, laimonassutkus commented on b_lambda_layer_common/source/python/b_lambda_layer_common/api_gateway/response_headers.py
> +        Audio file WAV content type header.
Bad docstring.

2020-12-18 08:47 UTC, laimonassutkus commented on b_lambda_layer_common/source/python/b_lambda_layer_common/api_gateway/response_headers.py
> +            # Indicate that response is of audio type, wav subtype.
Bad comment.

2020-12-18 08:51 UTC, laimonassutkus approved these changes

2020-12-18 08:52 UTC, merged