Add data caching functionality.
Biomapas/B.LambdaLayerCommon pull request #23
Opened 2021-05-31 14:44 UTC by simonasvaitkus

2021-05-31 16:13 UTC, robertasstankevicius requested changes

2021-05-31 16:13 UTC, robertasstankevicius commented on b_lambda_layer_common/source/python/b_lambda_layer_common/cache/data_cache.py
> +            logger.info('Cached data should be reset.')
When logging what is going to happen, use continuous present tense. Then if an error follows, you will know what action was being performed.
For example: Resetting cached data...

2021-05-31 16:13 UTC, robertasstankevicius commented on b_lambda_layer_common/source/python/b_lambda_layer_common/cache/data_cache.py
> +        :key kwargs: Keyword arguments that will be passed to func.
kwargs is also a parameter

2021-05-31 16:13 UTC, robertasstankevicius commented on b_lambda_layer_common/source/python/b_lambda_layer_common/cache/data_cache.py
> +            logger.info('Cached data should be reset.')
Don't forget the three dots ...

2021-05-31 16:23 UTC, robertasstankevicius approved these changes

2021-06-01 06:09 UTC, laimonassutkus requested changes

2021-06-01 06:09 UTC, laimonassutkus commented on b_lambda_layer_common/source/python/b_lambda_layer_common/cache/data_cache.py
> +class DataCache(Refreshable):
Rename DataCache to InMemoryDataCache.

2021-06-01 06:09 UTC, laimonassutkus commented on b_lambda_layer_common/source/python/b_lambda_layer_common/cache/data_cache.py
> +    from b_lambda_layer_common.source.python.b_lambda_layer_common.ssm.refreshable import Refreshable
Importing from ssm directory does not make any sense. Write a TODO comment that "Refreshable" class should be moved somewhere else.

2021-06-01 06:09 UTC, laimonassutkus commented on b_lambda_layer_common/source/python/b_lambda_layer_common/cache/data_cache.py
> +    from b_lambda_layer_common.ssm.refreshable import Refreshable
Importing from ssm directory does not make any sense. Write a TODO comment that "Refreshable" class should be moved somewhere else.

2021-06-01 06:09 UTC, laimonassutkus commented on b_lambda_layer_common/source/python/b_lambda_layer_common/cache/data_cache.py
> +    def __get_data(self, pointer: Union[str, Set[str]]) -> Any:
Add docstrings.

2021-06-01 06:09 UTC, laimonassutkus commented on b_lambda_layer_common/source/python/b_lambda_layer_common/cache/data_cache.py
> +    def __add_data(self, pointer: Union[str, Set[str]], func: Callable, *args, **kwargs) -> Any:
Add docstrings.

2021-06-01 08:21 UTC, laimonassutkus approved these changes

2021-06-01 08:21 UTC, merged